//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.14 at 10:43:01 AM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.co.za/mmiholdings/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.mmiholdings.schema;
